Use pytest as test runner
jazzband/django-analytical pull request #171
Opened 2020-11-29 21:44 UTC by smithdc1

* Used pytest to run tests within tox environments

* Removed test runner within setup.py

@bittner is this what you were thinking of to refactor the test runner out of setup.py?

2020-11-29 23:11 UTC, bittner requested changes
Not bad! That looks like a simple but effective change. Nice!  :+1: 

There are a few warnings in the `tox` runs, which however will be fix by PR #170, so we don't need to worry.

I made a few minor comments.

2020-11-29 23:11 UTC, bittner commented on setup.py
> +    from distutils.core import setup
I think this try-except is unneeded in modern Python 3.

2020-11-29 23:11 UTC, bittner commented on setup.cfg
> +DJANGO_SETTINGS_MODULE = analytical.tests.settings
Newline missing at end of line.

2020-11-29 23:11 UTC, bittner commented on tox.ini
> +    pytest
You can probably omit that as a dependency when you specify `pytest-django`.

2020-11-30 00:16 UTC, smithdc1 commented on setup.py
> -        from analytical.tests.utils import run_tests
I'll remove this function as well.

2020-11-30 00:28 UTC, bittner commented
Can you try to see if it's possible to also [remove the tests module](https://github.com/jazzband/django-analytical/blob/master/setup.py#L70-L71) from the packaging setup already?

```patch
--- a/setup.py
+++ b/setup.py
     packages=[
         'analytical',
         'analytical.templatetags',
-        'analytical.tests',
-        'analytical.tests.templatetags',
     ],
```

2020-11-30 00:33 UTC, bittner commented on setup.py
>  import analytical as package  # noqa
Move this import statement up to its regular place, where all the others are, then you'll be able to remove the `# noqa` safely. Now this should be possible.

2020-11-30 00:37 UTC, bittner commented on setup.py
>      pass
The `cmdclass` variable and this entire block can also go away if you move the docs generation into `tox.ini` ([see example](https://github.com/behave/behave-django/blob/master/tox.ini#L45-L50)). :rocket:

2020-11-30 00:40 UTC, bittner commented on setup.py
> -    django.setup()
Great! Having this removed, we should now be able to declare #117 to be fixed! :rocket:

2020-11-30 21:38 UTC, smithdc1 commented
Hi @bittner -- I've addressed your comments here. +7 / -72 seems like a nice win here. :rocket:

2020-11-30 21:40 UTC, bittner approved these changes
Sweet! I think we're ready to merge. :rocket: 

Good job! :+1:

2020-11-30 22:02 UTC, merged