Add support for Matomo user commands
jazzband/django-analytical pull request #191
Opened 2021-07-07 19:59 UTC by kesara

Ability to push custom commands to Matomo (#190) 
Might be a work around for #141

2021-07-11 08:17 UTC, bittner requested changes
Thanks for your effort! I just had a few comments, then I think this is ready for merging.

2021-07-11 08:17 UTC, bittner commented on tests/unit/test_tag_matomo.py
> +            assert var_code in r
Please split this up into 3 separate assert statements. Then the actual failing test will be easier to spot. Thank you!

2021-07-11 08:17 UTC, bittner commented on docs/services/matomo.rst
> +                            ['tackGoal', 1, 1000.01]]
Maybe like this?
```suggestion
        'matomo_commands': [
            ['setIgnoreClasses', 'no-tracking'],
            ['setDocumentTitle', 'foobar'],
            ['tackGoal', 1, 1000.01],
        ]
```

2021-07-12 14:19 UTC, SilverStrings024 commented
I actually have this in my PR to fix #141 but for some reason git isn't letting me push.

2021-07-13 06:41 UTC, kesara commented
@bittner Thanks for looking at my PR. Looks like #193 implements this in more generic way. So I'll close this PR.
@SilverStrings024 Can you add documentation with an example for on your PR?

2021-07-13 06:41 UTC, closed without merging

2021-07-13 15:10 UTC, SilverStrings024 commented
> @bittner Thanks for looking at my PR. Looks like #193 implements this in more generic way. So I'll close this PR.
> @SilverStrings024 Can you add documentation with an example for on your PR?

Yeah, I just need to get the points Bitner hit before I can merge. If you want, you can just take the code and install the package locally then modify it to use my PR. Until I have to time to hit all Bitners points, I can't work on this.

2021-07-13 15:11 UTC, SilverStrings024 commented
> > @bittner Thanks for looking at my PR. Looks like #193 implements this in more generic way. So I'll close this PR.
> > @SilverStrings024 Can you add documentation with an example for on your PR?
> 
> Yeah, I just need to get the points Bitner hit before I can merge and I'll add in the docs before pushing next. If you want, you can just take the code and install the package locally then modify it to use my PR. Until I have to time to hit all Bitners points, I can't work on this.

2021-07-13 15:11 UTC, SilverStrings024 commented
> > > @bittner Thanks for looking at my PR. Looks like #193 implements this in more generic way. So I'll close this PR.
> > > @SilverStrings024 Can you add documentation with an example for on your PR?
> > 
> > 

Yeah, I just need to get the points Bitner hit before I can merge and I'll add in the docs before pushing next. If you want, you can just take the code and install the package locally then modify it to use my PR. Until I have to time to hit all Bitners points, I can't work on this.