add more information about overriding identity to documentation
jazzband/django-analytical pull request #219
Opened 2022-07-14 10:23 UTC by PetrDlouhy

2022-07-14 10:38 UTC, PetrDlouhy commented
The docs expects, that #217 is merged.

2022-07-14 14:03 UTC, bittner requested changes
Looks good! – I hope you don't mind that I edit your changes so much.

2022-07-14 14:08 UTC, bittner commented on docs/features.rst
> +page.
```suggestion
If you want to change the identity only for specific provider use the
``*_identity`` context variable, where ``*``-prefix is the module name
of the specific provider.
```

2022-07-14 14:23 UTC, bittner commented
I believe, we should also mention [context processors](https://docs.djangoproject.com/en/4.0/ref/templates/api/#writing-your-own-context-processors) as an option.

## Example

```python
# FILE: myproject/context_processors.py
from django.conf import settings

def get_identity(request):
    return {
        'analytical_identity': 'some-value-here',
    }
```

With your project's `settings.py` like this:

```python
# FILE: myproject/settings.py
TEMPLATES = [
    {
        'OPTIONS': {
            'context_processors': [
                'myproject.context_processors.get_identity',
            ],
        },
    },
]
```

That allows you as a developer to leave your view code untouched _and_ make sure that the variable is injected for _all_ templates.

2022-07-15 10:42 UTC, PetrDlouhy commented
Hope all improvements are now in the PR.

2022-07-16 11:36 UTC, bittner requested changes
Great, thanks! Just another few corrections, then we're ready to merge.

2022-07-16 11:36 UTC, bittner commented on docs/features.rst
> +
```suggestion

```

Two empty lines should be enough.

2022-07-16 11:36 UTC, bittner commented on docs/features.rst
> +or in context proessor:
```suggestion
or by implementing a context processor:
```

2022-07-16 11:36 UTC, bittner commented on docs/features.rst
> +``*_identity`` context variable, where ``*``-prefix is the module name
```suggestion
``*_identity`` context variable, where the ``*`` prefix is the module name
```

2022-07-18 14:54 UTC, bittner approved these changes

2022-07-18 14:54 UTC, merged

2022-07-18 14:55 UTC, bittner commented
Shoot! I should have squashed the commits... :worried:

2022-07-18 14:55 UTC, bittner commented
Thanks for your contribution! :100: